# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0004_auto_20170824_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
